name: philiprehberger_rate_limiter
description: >-
  Token bucket, sliding window, and fixed window rate limiting for async operations
version: 0.7.0
homepage: https://philiprehberger.com/open-source-packages/dart/philiprehberger_rate_limiter
repository: https://github.com/philiprehberger/dart-rate-limiter
issue_tracker: https://github.com/philiprehberger/dart-rate-limiter/issues

environment:
  sdk: ^3.6.0

dev_dependencies:
  test: ^1.25.0
  lints: ">=5.0.0 <7.0.0"
